import { Metadata } from "next";

import dynamic from "next/dynamic";

const DynamicComponent = dynamic(() => import("@/containers/Home/Translate"));

export const metadata: Metadata = {
  title: "Nurd Studio | tranlate",
  description: "Generated by create next app",
};

export default function TranslatePage() {
  return <DynamicComponent />;
}
